services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - PYTHONPATH=/app
    depends_on:
      rabbitmq:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "25672:15672" # Management UI (original 15672 → 25672)
      - "25673:5672" 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    
  websocket:          # Si tienes WebSocket
    build: ./backend
    command: python -m app.infrastructure.websocket.ws_server
    ports:
      - "8001:8000"